export const ERROR_CODE = {
    INVALID_PARAMS: "INVALID_PARAMS",
    INVALID_MESSAGE: "INVALID_MESSAGE",
    INVALID_LEVEL: "INVALID_LEVEL",
    INVALID_EVENT_TIMESTAMP: "INVALID_EVENT_TIMESTAMP",

    INVALID_SEARCH_PARAMS: "INVALID_SEARCH_PARAMS",
    INVALID_SEARCH_LEVEL: "INVALID_SEARCH_LEVEL",
    INVALID_SEARCH_MESSAGE: "INVALID_SEARCH_MESSAGE",
    INVALID_SEARCH_FROM: "INVALID_SEARCH_FROM",
    INVALID_SEARCH_TO: "INVALID_SEARCH_TO",
    INVALID_SEARCH_RANGE: "INVALID_SEARCH_RANGE",

    READ_LOGS_FAILED: "READ_LOGS_FAILED",
    SEARCH_LOGS_FAILED: "SEARCH_LOGS_FAILED",

    WRITER_UNAVAILABLE: "WRITER_UNAVAILABLE"
} as const;